title: LoLz Lab
description: LoLz's Research Lab

url: http://lolz0309.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
#  - title: Contact
#    url: /contact

social:
  github: LoLz0309
  twitter: /
  facebook: /
  email: lolz0309@naver.com
  linkedin: /

google_analytics: "UA-58263416-1"

disqus:
    shortname: /
